---
title: "Capstone"
author: "Bianca Rodas"
date: "2025-04-16"
output: html_document
---

```{r libraries}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(viridis)
```


```{r read-in-data, eval=FALSE}
m1 <- read_csv("raw-data/master_m1.csv")
m2 <- read_csv("raw-data/master_m2.csv")
c1 <- read_csv("raw-data/master_c1.csv")
```

```{r cleaning-data, eval=FALSE}
m1 <- m1 |>
  mutate(buoy_id = "M1") |> #new column
  mutate(year = format(date, "%Y"), #new column by extracting year from POSIX format
         month = format(date, "%m"),
         day = format(date, "%d"))

m2 <- m2 |> 
  mutate(buoy_id = "M2")|> 
  mutate(year = format(date, "%Y"),
         month = format(date, "%m"),
         day = format(date, "%d"))

c1 <- c1 |>
  mutate(buoy_id = "C1")|> 
  mutate(year = format(date, "%Y"),
         month = format(date, "%m"),
         day = format(date, "%d"))

all_sites <- bind_rows(m1, m2, c1) #stacked each dataframe on top of each other

all_sites <- all_sites |> 
  mutate(enso_event = case_when(mei >= -0.5 & mei <= 0.5 ~ "Neutral",
                                TRUE ~ enso_event),#new variable called "Neutral" for certain years
         upwelling = if_else((direction >= 280.5 & direction <= 330.5 )& speed > 4.0, 1, 0)) |> #new column called upwelling based on certain conditions
  mutate(year = as.numeric(year), # changed variables from character to numeric
         month =as.numeric(month),
         day = as.numeric(day),
         week_month = ceiling(day(date) / 7),
         week = week(date))

write_csv(all_sites, "clean-data/master.csv") # downloads a csv from cleaned data
```


```{r read-in-master-data}
master <- read_csv("clean-data/master.csv")
upwelling <- read_csv("clean-data/Data Table Upwelling Onset & Duration - Sheet1.csv")
upwelling$enso_category <- factor(upwelling$enso_category)
upwelling$enso_category <- relevel(upwelling$enso_category, ref = "NO")
```


## Exploratory Data Analysis

**Upwelling Onset**

```{r}
ggplot(upwelling, aes(x=enso_category, y=upwelling_onset,fill=enso_category))+
  geom_violin(alpha=0.5, trim=F) +
  stat_summary(fun = median, geom = "crossbar", 
               width = 0.75, color = "red", fatten = 0)+
  geom_jitter()+
  labs(x="",
       y="Upwelling Onset (weeks)",
       caption= str_wrap("Figure. Violin plot showing the distribution of upwelling onset (in weeks of the year) across three ENSO categories: El Ni単o, La Ni単a, and Neutral years. The red horizontal line within each violin indicates the median onset week.",
                         width = 93))+
  theme_bw()+
  theme(legend.position="none",
        plot.caption = element_text(size = 11,
                                    hjust = 0,
                                    margin = margin(t = 10)))+
  scale_fill_viridis(discrete=T)+
  scale_x_discrete(labels = c("NO" = "Neutral", 
                              "EN" = "El Nino", 
                              "LN" = "La Nina"))

#ggsave(filename = "figures/upwelling_onset.png")
```


**Upwelling Duration**

```{r}
ggplot(upwelling, aes(x=enso_category, y=upwelling_duration,fill=enso_category))+
  geom_violin(alpha=0.5, trim=F) +
  stat_summary(fun = median, geom = "crossbar", 
               width = 0.65, color = "red", fatten = 0)+
  geom_jitter()+
  labs(x="",
       y="Upwelling Duration (weeks)",
       caption= str_wrap("Figure. Violin plot showing the distribution of upwelling duration (in weeks of the year) across three ENSO categories: El Ni単o, La Ni単a, and Neutral years. The red horizontal line within each violin indicates the median onset week.",
                         width = 93))+
  theme_bw()+
  theme(legend.position="none",
        plot.caption = element_text(size = 11,
                                    hjust = 0,
                                    margin = margin(t = 10)))+
  scale_fill_viridis(discrete=T)+
  scale_x_discrete(labels = c("NO" = "Neutral", 
                              "EN" = "El Nino", 
                              "LN" = "La Nina"))

#ggsave(filename = "figures/upwelling_duration.png")
```


## Analysis

**Upwelling Onset Model**

```{r}
onset <- glm(data=upwelling, upwelling_onset ~ enso_category)
summary(onset)
```



```{r}
plot(onset_model, 1, add.smooth=F)
plot(onset_model, 2)
plot(onset_model, 5, add.smooth=F)
shapiro.test(residuals(onset_model))
```




```{r}
duration <- glm(data=upwelling, upwelling_duration ~ enso_category)
summary(duration)
```

```{r}
plot(duration_model, 1, add.smooth=F)
plot(duration_model, 2)
plot(duration_model, 5, add.smooth=F)
shapiro.test(residuals(duration_model))
```




